### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MutualInformationFeatureSelector'

### ISSUE THREAD

**Issue by ssameeraafrin** [danielhomola/mifs#26]
Traceback (most recent call last):
  File "mifs.py", line 19, in <module>
    class MutualInformationFeatureSelector(object):
  File "mifs.py", line 86, in MutualInformationFeatureSelector
    import mifs
  File "/home/sathya/Downloads/mifs-master/mifs/mifs.py", line 19, in <module>
    class MutualInformationFeatureSelector(object):
  File "/home/sathya/Downloads/mifs-master/mifs/mifs.py", line 93, in MutualInformationFeatureSelector
    feat_selector = mifs.MutualInformationFeatureSelector()
AttributeError: 'module' object has no attribute 'MutualInformationFeatureSelector'

I got this error when I run it
if Ichanged to "from mifs import MutualInformationFeatureSelector" i am getting an import error:cannot import name MutualInformationFeatureSelector

**Comment by asha24choudhary** [comment]
I'm getting the same error :(. Can someone please help us
